spring:
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://192.168.31.17:5432/db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver